[2025-07-17T11:13:01.845+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-17T11:13:02.105+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bank_reviews_etl_and_analysis_pipeline.detect_language manual__2025-07-17T11:00:36.830164+00:00 [queued]>
[2025-07-17T11:13:02.123+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bank_reviews_etl_and_analysis_pipeline.detect_language manual__2025-07-17T11:00:36.830164+00:00 [queued]>
[2025-07-17T11:13:02.125+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-07-17T11:13:02.152+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): detect_language> on 2025-07-17 11:00:36.830164+00:00
[2025-07-17T11:13:02.164+0000] {standard_task_runner.py:72} INFO - Started process 1794 to run task
[2025-07-17T11:13:02.171+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bank_reviews_etl_and_analysis_pipeline', 'detect_language', 'manual__2025-07-17T11:00:36.830164+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/dag_load_reviews.py', '--cfg-path', '/tmp/tmp7wv77tqm']
[2025-07-17T11:13:02.175+0000] {standard_task_runner.py:105} INFO - Job 62: Subtask detect_language
[2025-07-17T11:13:02.282+0000] {task_command.py:467} INFO - Running <TaskInstance: bank_reviews_etl_and_analysis_pipeline.detect_language manual__2025-07-17T11:00:36.830164+00:00 [running]> on host 569ba507bc01
[2025-07-17T11:13:02.480+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohammed' AIRFLOW_CTX_DAG_ID='bank_reviews_etl_and_analysis_pipeline' AIRFLOW_CTX_TASK_ID='detect_language' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T11:00:36.830164+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-17T11:00:36.830164+00:00'
[2025-07-17T11:13:02.516+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-07-17T11:13:02.518+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-07-17T11:13:02.520+0000] {logging_mixin.py:190} INFO - Current task name:detect_language state:running start_date:2025-07-17 11:13:02.107252+00:00
[2025-07-17T11:13:02.521+0000] {logging_mixin.py:190} INFO - Dag name:bank_reviews_etl_and_analysis_pipeline and current dag run status:running
[2025-07-17T11:13:02.523+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-17T11:13:02.530+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-17T11:13:02.536+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/detect_language.py']
[2025-07-17T11:13:02.586+0000] {subprocess.py:99} INFO - Output:
[2025-07-17T11:13:03.023+0000] {subprocess.py:106} INFO - ✅ Connexion réussie à la base de données Aiven PostgreSQL.
[2025-07-17T11:13:03.025+0000] {subprocess.py:106} INFO - ✅ Connexion réussie à la base de données.
[2025-07-17T11:13:03.028+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-17T11:13:03.030+0000] {subprocess.py:106} INFO -   File "/opt/***/scripts/detect_language.py", line 29, in <module>
[2025-07-17T11:13:03.033+0000] {subprocess.py:106} INFO -     cur.execute("""
[2025-07-17T11:13:03.034+0000] {subprocess.py:106} INFO - psycopg2.errors.InvalidSchemaName: schema "transactional" does not exist
[2025-07-17T11:13:03.036+0000] {subprocess.py:106} INFO - 
[2025-07-17T11:13:03.064+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-17T11:13:03.084+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-17T11:13:03.094+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-07-17T11:13:03.096+0000] {logging_mixin.py:190} INFO - Task start:2025-07-17 11:13:02.107252+00:00 end:2025-07-17 11:13:03.093946+00:00 duration:0.986694
[2025-07-17T11:13:03.097+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): detect_language> dag:<DAG: bank_reviews_etl_and_analysis_pipeline> dagrun:<DagRun bank_reviews_etl_and_analysis_pipeline @ 2025-07-17 11:00:36.830164+00:00: manual__2025-07-17T11:00:36.830164+00:00, state:running, queued_at: 2025-07-17 11:00:37.881556+00:00. externally triggered: True>
[2025-07-17T11:13:03.098+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-07-17T11:13:03.099+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=bank_reviews_etl_and_analysis_pipeline, task_id=detect_language, run_id=manual__2025-07-17T11:00:36.830164+00:00, execution_date=20250717T110036, start_date=20250717T111302, end_date=20250717T111303
[2025-07-17T11:13:03.193+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-17T11:13:03.197+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 62 for task detect_language (Bash command failed. The command returned a non-zero exit code 1.; 1794)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-17T11:13:03.232+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-17T11:13:03.295+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-17T11:13:03.307+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
