[2025-07-17T10:41:29.107+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-17T10:41:30.558+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bank_reviews_etl_and_analysis_pipeline.convertir_date_relative manual__2025-07-17T00:17:54.106541+00:00 [queued]>
[2025-07-17T10:41:30.681+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bank_reviews_etl_and_analysis_pipeline.convertir_date_relative manual__2025-07-17T00:17:54.106541+00:00 [queued]>
[2025-07-17T10:41:30.690+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-07-17T10:41:30.937+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): convertir_date_relative> on 2025-07-17 00:17:54.106541+00:00
[2025-07-17T10:41:31.041+0000] {standard_task_runner.py:72} INFO - Started process 954 to run task
[2025-07-17T10:41:31.072+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bank_reviews_etl_and_analysis_pipeline', 'convertir_date_relative', 'manual__2025-07-17T00:17:54.106541+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag_load_reviews.py', '--cfg-path', '/tmp/tmpl486tcdn']
[2025-07-17T10:41:31.087+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask convertir_date_relative
[2025-07-17T10:41:31.474+0000] {task_command.py:467} INFO - Running <TaskInstance: bank_reviews_etl_and_analysis_pipeline.convertir_date_relative manual__2025-07-17T00:17:54.106541+00:00 [running]> on host 569ba507bc01
[2025-07-17T10:41:32.183+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohammed' AIRFLOW_CTX_DAG_ID='bank_reviews_etl_and_analysis_pipeline' AIRFLOW_CTX_TASK_ID='convertir_date_relative' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T00:17:54.106541+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-17T00:17:54.106541+00:00'
[2025-07-17T10:41:32.216+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-07-17T10:41:32.245+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-07-17T10:41:32.249+0000] {logging_mixin.py:190} INFO - Current task name:convertir_date_relative state:running start_date:2025-07-17 10:41:30.564507+00:00
[2025-07-17T10:41:32.254+0000] {logging_mixin.py:190} INFO - Dag name:bank_reviews_etl_and_analysis_pipeline and current dag run status:running
[2025-07-17T10:41:32.305+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-17T10:41:32.369+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-17T10:41:32.449+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/convertir_date_relative.py']
[2025-07-17T10:41:32.587+0000] {subprocess.py:99} INFO - Output:
[2025-07-17T10:41:33.761+0000] {subprocess.py:106} INFO - ❌ Échec de la connexion : connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-07-17T10:41:33.795+0000] {subprocess.py:106} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-07-17T10:41:33.797+0000] {subprocess.py:106} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-07-17T10:41:33.802+0000] {subprocess.py:106} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-07-17T10:41:33.817+0000] {subprocess.py:106} INFO - 
[2025-07-17T10:41:33.863+0000] {subprocess.py:106} INFO - ❌ Erreur : Échec de la connexion à la base de données.
[2025-07-17T10:41:33.881+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-17T10:41:33.893+0000] {subprocess.py:106} INFO -   File "/opt/***/scripts/convertir_date_relative.py", line 143, in <module>
[2025-07-17T10:41:33.928+0000] {subprocess.py:106} INFO -     if cur:
[2025-07-17T10:41:33.940+0000] {subprocess.py:106} INFO -        ^^^
[2025-07-17T10:41:33.956+0000] {subprocess.py:106} INFO - NameError: name 'cur' is not defined. Did you mean: 'chr'?
[2025-07-17T10:41:33.989+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-17T10:41:34.063+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-17T10:41:34.136+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-07-17T10:41:34.145+0000] {logging_mixin.py:190} INFO - Task start:2025-07-17 10:41:30.564507+00:00 end:2025-07-17 10:41:34.131334+00:00 duration:3.566827
[2025-07-17T10:41:34.151+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): convertir_date_relative> dag:<DAG: bank_reviews_etl_and_analysis_pipeline> dagrun:<DagRun bank_reviews_etl_and_analysis_pipeline @ 2025-07-17 00:17:54.106541+00:00: manual__2025-07-17T00:17:54.106541+00:00, state:running, queued_at: 2025-07-17 00:17:54.887499+00:00. externally triggered: True>
[2025-07-17T10:41:34.158+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-07-17T10:41:34.168+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=bank_reviews_etl_and_analysis_pipeline, task_id=convertir_date_relative, run_id=manual__2025-07-17T00:17:54.106541+00:00, execution_date=20250717T001754, start_date=20250717T104130, end_date=20250717T104134
[2025-07-17T10:41:34.451+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-17T10:41:34.476+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 54 for task convertir_date_relative (Bash command failed. The command returned a non-zero exit code 1.; 954)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-17T10:41:34.749+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-17T10:41:35.059+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-17T10:41:35.169+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
